import { withBasePath } from '@/lib/deployment-path';
import { SiteFooter } from '../../../components/site-footer';

const figma='https://www.figma.com/proto/pfQwL0GWX9n8DvjlI6WJfy/Teaverse_final-project_CHAGEE?node-id=0-1&t=9HTimHR9blddETYj-1';
const base='/assets/chagee/';
export function ChageeCaseStudy(){return <main className="chg" id="chg-top"><header className="chg-nav"><a href={withBasePath('/')}>← 返回首页</a><span>TEAVERSE — CHAGEE</span><a href={withBasePath('/Li-Sijing-Resume.pdf')} target="_blank">查看简历 ↗</a></header>
<section className="chg-hero"><div className="chg-meta"><p>网站设计 / Figma 原型</p><p>课程概念项目</p></div><h1>TEAVERSE<br/><em>— CHAGEE</em></h1><figure><img src={withBasePath(`${base}home.webp`)} alt="TEAVERSE CHAGEE 网站首页设计"/><figcaption>HOME / 高保真界面 / Figma</figcaption></figure><div className="hero-project-info"><p>新中式品牌网站概念</p><p>界面设计 · 视觉风格设计</p><a href={figma} target="_blank" rel="noreferrer">查看 Figma 原型 ↗</a></div></section>
<section className="chg-overview"><div className="chg-heading"><span>02</span><h2>项目概览</h2></div><p className="chg-lead">以“新中式”为核心视觉方向，将东方茶文化、品牌故事与现代网页体验结合，完成从视觉概念、信息架构到高保真交互原型的设计输出。</p><div className="chg-facts"><article><h3>项目性质</h3><p>基于霸王茶姬品牌形象完成的非官方网站课程概念设计。</p></article><article><h3>我的角色</h3><p>信息层级梳理、视觉方向、界面设计、基础组件与 Figma 高保真交互原型。</p></article><article><h3>设计目标</h3><p>延续东方茶文化表达，同时帮助用户更清晰地了解品牌、浏览产品并建立联系。</p></article></div></section>
<section className="chg-challenge"><div className="chg-heading"><span>03</span><h2>设计挑战</h2></div><ol><li><b>01</b><h3>把品牌视觉转化为网页语言</h3><p>避免直接堆叠传统纹样，在东方意象与现代网页阅读之间找到平衡。</p></li><li><b>02</b><h3>让品牌内容与产品信息共存</h3><p>建立清晰层级，让文化叙事不影响实际浏览效率。</p></li><li><b>03</b><h3>保持多页面体验一致</h3><p>通过导航、字体、色彩、组件与页脚连接不同功能页面。</p></li></ol></section>
<section className="chg-ia"><div className="chg-heading light"><span>04</span><h2>信息架构</h2></div><p>网站围绕“了解品牌 → 浏览产品 → 深入故事 → 获取资讯或建立联系”的路径展开。</p><div className="ia-flow"><span>HOME<small>第一印象</small></span><i>→</i><span>PRODUCTS<small>浏览产品</small></span><i>→</i><span>ABOUT<small>品牌故事</small></span><i>→</i><span>MEDIA / CONTACT<small>资讯与沟通</small></span></div><figure><img loading="lazy" src={withBasePath(`${base}overview.webp`)} alt="五个页面的 Figma 原型总览"/><figcaption>原型总览 / 五个核心页面</figcaption></figure></section>
<section className="chg-visual"><div className="chg-heading"><span>05</span><h2>视觉方向</h2></div><div className="visual-copy"><h3>新中式的现代转译</h3><p>没有将网站设计成传统元素的集合，而是通过低饱和自然色、纵向栅格、大图与留白建立东方氛围。编辑感衬线标题与清晰无衬线正文，在品牌叙事和实际阅读之间保持平衡。</p></div><div className="palette"><span className="olive">深橄榄绿</span><span className="orange">暖橙红</span><span className="cream">米白色</span><span className="tea">浅茶绿</span></div></section>
<section className="chg-pages"><div className="chg-heading"><span>06</span><h2>核心页面</h2></div><article className="page-study home"><div><span>01 / HOME</span><h3>建立品牌第一印象</h3><p>以产品主视觉为中心，再依次连接品牌简介、产品系列与门店空间。</p></div><img loading="lazy" src={withBasePath(`${base}home.webp`)} alt="CHAGEE 首页设计"/></article><article className="page-study about"><img loading="lazy" src={withBasePath(`${base}about.webp`)} alt="CHAGEE 品牌故事页面"/><div><span>02 / ABOUT</span><h3>传递文化与品牌价值</h3><p>通过图文交错、细节摄影和米白留白，降低长内容的阅读压力。</p></div></article><div className="page-pair"><figure><img loading="lazy" src={withBasePath(`${base}menu.webp`)} alt="CHAGEE 产品菜单页面"/><figcaption>PRODUCTS / 分类与产品浏览</figcaption></figure><figure><img loading="lazy" src={withBasePath(`${base}news.webp`)} alt="CHAGEE 品牌资讯页面"/><figcaption>MEDIA / 时间线资讯结构</figcaption></figure><figure><img loading="lazy" src={withBasePath(`${base}contact.webp`)} alt="CHAGEE 联系页面"/><figcaption>CONTACT / 表单与联系入口</figcaption></figure></div></section>
<section className="chg-prototype"><div className="chg-heading light"><span>07</span><h2>Prototype</h2></div><p>原型包含顶部导航、页面标题、按钮与状态、产品信息卡片、社交图标、联系表单和页脚等可复用组件，以统一多个页面的浏览体验。</p><figure><img loading="lazy" src={withBasePath(`${base}overview.webp`)} alt="TEAVERSE CHAGEE Figma 完整原型"/></figure><a href={figma} target="_blank" rel="noreferrer">在 Figma 中查看完整原型 ↗</a></section>
<section className="chg-end"><p>08 / 项目反思</p><blockquote>这个项目让我认识到，品牌网站不仅需要“看起来符合品牌”，也要帮助用户高效完成信息浏览。视觉风格、内容结构和交互体验需要共同服务于品牌表达。</blockquote><div className="next-note"><span>可继续迭代</span><p>补充移动端与平板设计；对产品分类和导航路径进行用户测试；完善无障碍与表单反馈。</p></div></section><SiteFooter /></main>}
