import { SiteFooter } from '../../../components/site-footer';

const base='/assets/xiaohongshu/';
const selected=[['dunhuang.webp','敦煌 / 实用攻略'],['taipei.webp','台北 / 旅行叙事'],['mini-01.webp','巴厘岛 / 氛围表达'],['tamsui.webp','淡水北投 / 旅行叙事'],['xinjiang.webp','新疆 / 实用攻略'],['tainan.webp','台南 / 旅行叙事'],['mini-02.webp','Mini Vlog / Visual Diary'],['hualien.webp','花莲 / 旅行叙事']];
export function XiaohongshuCaseStudy(){return <main className="xhs" id="xhs-top"><header className="xhs-nav"><a href="/">← 返回首页</a><span>小红书个人内容运营</span><a href="/Li-Sijing-Resume.pdf" target="_blank">查看简历 ↗</a></header>
<section className="xhs-hero"><div className="xhs-hero-meta"><p>内容策划 / Social Media / 视觉叙事</p><p>个人项目 / 持续更新</p></div><p className="xhs-ghost">XIAOHONGSHU</p><h1>小红书<br/>个人内容运营</h1><figure><img src={`${base}dunhuang.webp`} alt="敦煌四天三夜旅行攻略内容"/><figcaption>敦煌 / 旅行攻略 / 视觉与信息组织</figcaption></figure><a className="xhs-primary-link" href="https://xhslink.cn/m/2zsavbquSS2" target="_blank" rel="noreferrer">查看我的小红书 ↗</a></section>
<section className="xhs-overview"><div className="xhs-heading"><span>02</span><h2>账号概览</h2></div><div className="xhs-overview-copy"><p>以旅行内容为核心，通过旅行 Vlog、目的地体验和氛围化图文，记录不同地区的风景、文化与个人感受。内容既关注路线、景点等实用信息，也重视旅行过程中的情绪表达与视觉呈现。</p></div><div className="account-facts"><article><span>定位</span><h3>旅行与生活体验</h3><p>从单一旅行记录，逐步发展为更具人物特点的个人内容表达。</p></article><article><span>内容方向</span><h3>攻略 / Vlog / 氛围表达</h3><p>根据内容目标调整信息密度、叙事节奏与视觉语言。</p></article><article className="account-number"><span>已确认账号数据</span><strong>9,000+</strong><p>累计赞与收藏</p></article></div><figure className="account-visual"><img loading="lazy" src={`${base}home-grid.webp`} alt="小红书账号作品主页视觉"/><figcaption>账号内容矩阵 / 主页视觉</figcaption></figure></section>
<section className="xhs-system"><div className="xhs-heading"><span>03</span><h2>内容体系</h2></div><div className="system-intro">同样是旅行，不同内容承担不同任务：讲完整的经历、解决实际问题，或留下一个值得共鸣的情绪瞬间。</div><div className="system-list"><article><b>01</b><p>TRAVEL STORY</p><h3>旅行叙事</h3><p>用完整过程和人物感受组织 Vlog。重点不是景点罗列，而是让路线、转场和当下情绪共同形成观看节奏。</p></article><article><b>02</b><p>USEFUL GUIDE</p><h3>实用攻略</h3><p>从用户可能搜索和收藏的问题出发，把路线、住宿、交通和体验拆成清晰信息，同时保留目的地质感。</p></article><article><b>03</b><p>VISUAL DIARY</p><h3>氛围表达</h3><p>通过画面、音乐和短文案建立情绪。弱化信息负担，强调光线、人物与旅行中的片刻感受。</p></article></div></section>
<section className="xhs-selected"><div className="xhs-heading light"><span>04</span><h2>精选内容</h2></div><div className="xhs-scrap">{selected.map(([src,label],i)=><figure className={`xhs-piece xp-${i+1}`} key={src}><img loading="lazy" src={`${base}${src}`} alt={label}/><figcaption>{String(i+1).padStart(2,'0')} / {label}</figcaption></figure>)}<span className="scribble">travel<br/>as a story</span></div></section>
<section className="xhs-workflow"><div className="xhs-heading"><span>05</span><h2>我的内容工作流</h2></div><p className="workflow-lead">从“这趟旅行有什么值得讲”开始，到发布后的反馈复盘结束。每一步都围绕内容价值与表达方式做选择。</p><ol>{[['选题','从目的地、个人体验和用户需求中找到内容角度。'],['Hook / 开头','先回答为什么值得看，用画面、问题或冲突建立第一印象。'],['拍摄','为信息、叙事和氛围分别准备素材，而不是只记录行程。'],['剪辑','根据内容类型控制节奏：攻略清晰，Vlog 连贯，氛围内容留白。'],['封面','提炼最能代表内容价值的画面与标题，兼顾辨识度和信息传达。'],['发布','根据内容目标组织标题、正文与发布节奏。'],['复盘','结合点赞、收藏和评论反馈，检查封面、标题与内容节奏。']].map(([title,body],i)=><li key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></li>)}</ol></section>
<section className="xhs-cases"><div className="xhs-heading"><span>06</span><h2>内容案例</h2></div><article className="case case-guide"><img loading="lazy" src={`${base}dunhuang.webp`} alt="敦煌攻略"/><div><span>CASE 01 / USEFUL GUIDE</span><h3>敦煌 4 天 3 夜</h3><p><b>为什么选：</b>淡季旅行具有明确搜索需求，也能提供与旺季不同的体验视角。</p><p><b>如何组织：</b>以天数和路线为信息骨架，将交通、住宿、门票与真实体感放进同一叙事。</p><p><b>用户价值：</b>降低行程规划成本，同时帮助用户判断淡季敦煌是否适合自己。</p></div></article><article className="case case-vlog"><img loading="lazy" src={`${base}taipei.webp`} alt="台北旅行 Vlog"/><div><span>CASE 02 / TRAVEL STORY</span><h3>落地台北的第一天</h3><p><b>为什么选：</b>“到达”天然具有时间线和人物感，适合建立系列开篇。</p><p><b>视觉思路：</b>用在地细节、人物出镜与手写标注连接旅行过程，让 Vlog 保持个人视角。</p><p><b>用户价值：</b>既提供目的地感受，也让观众获得陪伴式观看体验。</p></div></article><article className="case case-diary"><video controls preload="none" playsInline poster={`${base}mini-02.webp`}><source src={`${base}mini-vlog.mp4`} type="video/mp4"/></video><div><span>CASE 03 / VISUAL DIARY</span><h3>Mini Vlog</h3><p><b>为什么选：</b>并非每段旅行都需要完整攻略，短内容更适合承载一个场景或情绪。</p><p><b>剪辑思路：</b>让画面、音乐和简短文字共同建立氛围，减少解释性信息。</p><p><b>用户价值：</b>提供审美与情绪共鸣，也丰富账号在攻略和长 Vlog 之外的观看节奏。</p></div></article></section>
<section className="xhs-reflection"><p>07 / 复盘</p><blockquote>从单纯记录旅行，到逐步形成旅行叙事、实用攻略与氛围表达三个方向。变化不只是内容分类更清楚，也体现在选题判断、信息组织、封面表达和个人视觉语言开始互相支持。</blockquote></section>
<section className="xhs-next"><a href="/work/teaverse-chagee"><span>08 / 下一个项目</span>TEAVERSE — CHAGEE →</a></section><SiteFooter /></main>}
